name: portfoy_app
description: "Cebeci"
publish_to: 'none'
version: 1.0.0+22

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  url_launcher: ^6.2.4
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  shimmer: ^3.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  socket_io_client: ^3.0.0
  rename: ^3.1.0
  flutter_native_splash: ^2.4.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/playstore.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/playstore.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/playstore.png
  android: true
  ios: true
  fullscreen: true

flutter:
  assets:
    - assets/
  uses-material-design: true